extend-include = ["*.ipynb"]

[format]
docstring-code-format = true

[lint]
select = [
    "ALL", # Default to all new rules. More maintenance, but more features
]
unfixable = [
    "ERA001", # Commented out code
]
ignore = [
    "COM812", # Conflicts with formatter (trailing comma)
    "D100",   # Missing docstring in public module
    "D101",   # Missing docstring in public class
    "D102",   # Missing docstring in public method
    "D103",   # Missing docstring in public function
    "D104",   # Missing docstring in public package
    "D105",   # Missing docstring in magic method
    "D106",   # Missing docstring in public nested class
    "D107",   # Missing docstring in __init__
    "D203",   # One blank line before class docstring (conflicts with D211)
    "D213",   # Multi-line summary on second line (conflicts with D212)
    "E501",   # Line length (otherwise enforced by formatter)
    "FIX002", # Prevents TODO comments, which are useful
    "ISC001", # Conflicts with formatter
    "TD002",  # Prevents authorless TODO comments, which is annoying
    "TD003",  # Prevents issueless TODO
]

[lint.extend-per-file-ignores]
"test_*" = [
    "ANN201", # Require function return types
    "ANN202", # Require inner function return types
    "S101",   # Prohibit assert keyword
    "TID252", # Prohibit relative imports
]
"*.pyi" = [
    "ANN401", # Require argument annotations
]
